# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

test_script:
  - cmd: npm t

os: Windows Server 2012 R2

build: off

version: "{build}"
